import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

// Configurar Geist Sans
const geistSans = localFont({
  src: [
    {
      path: "./fonts/GeistVF.woff",
      weight: "100 900",
    },
  ],
  variable: "--font-geist-sans",
});

// Configurar Geist Mono
const geistMono = localFont({
  src: [
    {
      path: "./fonts/GeistMonoVF.woff",
      weight: "100 900",
    },
  ],
  variable: "--font-geist-mono",
});

// Metadata de la Aplicación
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Componente Principal
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
